- source/ports/node_port/package/.gitignore
- source/ports/node_port/package/binding.gyp
- source/ports/node_port/package/include/metacall/metacall.h
- source/ports/node_port/package/include/metacall/metacall_allocator.h
- source/ports/node_port/package/include/metacall/metacall_api.h
- source/ports/node_port/package/include/metacall/metacall_def.h
- source/ports/node_port/package/include/metacall/metacall_features.h
- source/ports/node_port/package/include/metacall/metacall_fork.h
- source/ports/node_port/package/include/metacall/metacall_loaders.h
- source/ports/node_port/package/include/metacall/metacall_log.h
- source/ports/node_port/package/include/metacall/metacall_value.h
- source/ports/node_port/package/include/metacall/metacall_version.h
- source/ports/node_port/package/index.js
- source/ports/node_port/package/lib.js
- source/ports/node_port/package/package-lock.json
- source/ports/node_port/package/package.json
- source/ports/node_port/package/scripts/preinstall.js
- source/ports/node_port/package/src/nodeport.cc
- source/ports/node_port/package/test.js
Created a working NodeJs Port for Metacall Core... Ehhhhhhhhhhhhhh, should I say more?!! :)
> Commit NodeJs Port Source Codes

- source/loaders/rs_loader/.TODO
- source/loaders/rs_loader/.gitignore
- source/loaders/rs_loader/Cargo.toml
- source/loaders/rs_loader/src/defer.rs
- source/loaders/rs_loader/src/lib.rs
The Cmake file still needs to be added and details for things that should be done are in the .TODO.
It's maintainer editable so feel free to add them on your own, I will likely be a bit busy this week to be much help.
Also there needs to be some formatting but that would need your input on how you want the files to be formatted.
cc: @viferga
> Add rust port

- CONTRIBUTORS
- source/ports/rs_port/Cargo.toml
- source/ports/rs_port/README.md
- source/ports/rs_port/src/lib.rs
Fixes some, but not all issues mentioned in #56. I made my changes in small commits, so you can see what I did step-by-step.
> Rust improvements

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Fixes https://github.com/metacall/core/issues/89
> Add Issues and PR Templates

- source/loaders/py_loader/source/py_loader_impl.c
This PR implements the changes suggested in  #94. It is not 100% exhaustive, but does fix the majority of occurrences of these issues. I have also added improved comments in some places.
> Refactor Python loader

- docs/README.md
Fixed few grammar and spelling mistakes.  I like the docs by the way.
> Fix some Grammar/Spelling mistakes

- source/reflect/source/reflect_exception.c
Implemented copy for exeception_create function. 
> completed copy for exception_create

- source/loaders/llvm_loader/source/llvm_loader_impl.cpp
Added code to disable undesirable LLVM warnings, implemented some types except buffers and pointers, initialized the LLVMContext, and fixed the return error.
> Removed LLVM warnings, implemented some types, and fixed some errors

- source/loaders/cs_loader/include/cs_loader/netcore_linux.h
- source/loaders/cs_loader/source/netcore_linux.cpp
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the style guidelines (clang-format) of this project.
- [ x] I have performed a self-review of my own code.
- [ x] My changes generate no new warnings.
- [ x] I have tested the tests implicated (if any) by my own code and they pass (`make test` or `ctest -VV -R <test-name>`).
- [ x] I have tested my code with `OPTION_BUILD_SANITIZER` and `OPTION_TEST_MEMORYCHECK`. 
> Now unload the ClrCore lib in linux implementation

- docs/README.md
Updated the Build Status Badge of [Platform Support](https://github.com/metacall/core/blob/develop/docs/README.md#7-platform-support)
Updated Look:
> Updated Build Status Badge

- source/loaders/java_loader/bootstrap/bootstrap.java
- source/loaders/java_loader/source/java_loader_impl.cpp
Adding the Bootstrap. java to the initial development of java Loader
> Initial bootstrap java file setup

- CONTRIBUTORS
- source/loaders/java_loader/bootstrap/lib/bootstrap.java
- source/loaders/java_loader/source/java_loader_impl.cpp
- source/tests/metacall_java_test/source/metacall_java_test.cpp
- java loader execution_path - Add execution path function and bootstrap_execution_path functions
- java_load_from_file - compiling class and storing in an handle 
> Dynamic execution path and load from file function

- source/loaders/wasm_loader/CMakeLists.txt
- source/loaders/wasm_loader/source/wasm_loader_impl.c
This PR implements initialization, handle loading (from a buffer or from a file) and function discovery.
> WebAssembly loader: Initialization, handle loading and function discovery

- source/loaders/java_loader/bootstrap/lib/bootstrap.java
- source/loaders/java_loader/source/java_loader_impl.cpp
- source/scripts/java/fibonacci/source/Test.java
- source/tests/metacall_java_test/source/metacall_java_test.cpp
- Added java_object_interface_singleton
- Added java_class_interface_singleton
- Changed jobject in handle_type struct to jobjectarray
- Added iterator for working of discover function
> Java discover function

- source/loaders/java_loader/bootstrap/lib/bootstrap.java
- source/loaders/java_loader/source/java_loader_impl.cpp
- Fixed jobject array issue, earlier conversation to jobject array was wrong and not working
- Able to iterate over handle with class and register each with metacall.
> Java discover class function to register classes

- source/loaders/java_loader/bootstrap/lib/bootstrap.java
- source/loaders/java_loader/source/java_loader_impl.cpp
- source/tests/metacall_java_test/source/metacall_java_test.cpp
- Dynamic classpath loading for java 9+ to allow JNI access classes dynamically.
- Class singleton Create, Constructor and Get methods.
- Metacall java test to initialize test class with data types and get data values
- supported types Boolean, Char, short, int, long, float, double and strings.
> Java loader class singleton create, constructor and get methods

- source/loaders/java_loader/bootstrap/lib/bootstrap.java
- source/loaders/java_loader/source/java_loader_impl.cpp
- source/tests/metacall_java_test/source/metacall_java_test.cpp
- Java Class Singleton Set static Field Value
- Java Object singleton Get non static field value
- Java Object singleton Set non static field value
- Supported data types are Boolean, Char, Short, Int, Long, Float, Double and String.
- Supporting test cases for each value.
> Java singleton class and Object Create, Get and Set methods

- source/loaders/java_loader/bootstrap/lib/bootstrap.java
- source/loaders/java_loader/source/java_loader_impl.cpp
- source/tests/metacall_java_test/source/metacall_java_test.cpp
> java load from memory implementation

- source/loaders/java_loader/bootstrap/lib/bootstrap.java
- source/loaders/java_loader/source/java_loader_impl.cpp
> java loader field attribute initial implementation

- source/loaders/java_loader/source/java_loader_impl.cpp
> java object get, set and invoke methods

- source/loaders/rs_loader/rust/src/lifecycle/clear.rs
- source/loaders/rs_loader/rust/src/lifecycle/destroy.rs
- source/loaders/rs_loader/rust/src/lifecycle/discover.rs
- source/loaders/rs_loader/rust/src/lifecycle/execution_path.rs
- source/loaders/rs_loader/rust/src/lifecycle/initialize.rs
- source/loaders/rs_loader/rust/src/lifecycle/load_from_file.rs
- source/loaders/rs_loader/rust/src/lifecycle/load_from_memory.rs
- source/loaders/rs_loader/rust/src/lifecycle/load_from_package.rs
Format code and remove unused stuff
Operation has done in the src/lifecycle directory.
> Format code and remove unused stuff

- source/loaders/c_loader/source/c_loader_impl.cpp
Implemented load_from_file and discover using tcc and clang
> load_from _file for C-Loader based on TCC and clang

- source/loaders/c_loader/source/c_loader_impl.cpp
Dynamic function calling at runtime using LIBFFI in C-Loader
> Implemented function_invoke for C-Loader using LIBFFI 

- source/loaders/rs_loader/rust/.vscode/settings.json
- source/loaders/rs_loader/rust/compiler/Cargo.toml
Fix rust-analyzer Rustc_interface support in rs_loader_impl
> Fix rust-analyzer Rustc_interface support in rs_loader_impl

- source/loaders/rs_loader/rust/api/src/lib.rs
- source/loaders/rs_loader/rust/compiler/Cargo.toml
- source/loaders/rs_loader/rust/compiler/src/file.rs
- source/loaders/rs_loader/rust/compiler/src/lib.rs
- source/loaders/rs_loader/rust/compiler/src/registrator.rs
- source/loaders/rs_loader/rust/src/lifecycle/discover.rs
- source/loaders/rs_loader/rust/src/lifecycle/load_from_package.rs
- source/loaders/rs_loader/rust/src/lifecycle/loader.rs
Implement function_impl for creating functions for core in rs_loader_impl
> Implement function_impl for creating functions for core in rs_loader_impl

- .gitpod.yml
- docs/README.md
As we all know [`metacall/core`](https://github.com/metacall/core) was part of GSoC'21 & will be part of GSoC'22 and so on ..... 
For Me as a beginner, the major block is to set up the project locally. Like Testing the metacall cli, their loaders to run, load & test.
So, Instead of configuring a local setup, we can use [Gitpod](https://www.gitpod.io/), an automated cloud dev environment.
After the merging of this PR, you can directly run this repo. in your browser. It is will be ready to run, build, test & ship 🚀  the new features.
[Detailed Docs about the Gitpod](https://github.com/Siddhant-K-code/core/blob/8267c67ceb839d89914d734b358439be8b699e43/docs/README.md#6-build-system)
> ⭐  This Will Help New Contributors to start building & setting up easily.
> gitpodify the metacall/core 🚀 

- docs/README.md
created a new section 6.4 for gitpod related docs
> chore(docs): 6.4-build on cloud - gitpod

- docs/README.md
Adds inside the documentation, ArchLinux package from the AUR and step to install and use it.
> Update installation to add ArchLinux AUR metcall pkg

- .github/CONTRIBUTING.md
- docs/README.md
See commits and files changed - they are quite small.
> Fix minor issue in main doc and contributing guidelines

- source/loaders/rs_loader/rust/api/Cargo.toml
- source/loaders/rs_loader/rust/api/src/lib.rs
- source/loaders/rs_loader/rust/compiler/Cargo.toml
- source/loaders/rs_loader/rust/compiler/src/lib.rs
- source/loaders/rs_loader/rust/compiler/src/memory.rs
- source/loaders/rs_loader/rust/compiler/src/registrator.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/array.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/map.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/mod.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/number.rs
- source/loaders/rs_loader/rust/src/lifecycle/discover.rs
- source/loaders/rs_loader/rust/src/lifecycle/initialize.rs
- source/loaders/rs_loader/rust/src/lifecycle/load_from_memory.rs
- source/loaders/rs_loader/rust/src/lifecycle/loader.rs
- source/scripts/rust/basic/source/basic.rs
- source/tests/metacall_rust_test/source/metacall_rust_test.cpp
- tools/metacall-configure.sh
Enable Rust load from memory.
Add support for numbers, array and map.
> Enable Rust load from memory.

- source/loaders/rs_loader/rust/compiler/src/lib.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/mod.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/number.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/string.rs
- source/loaders/rs_loader/rust/src/lifecycle/initialize.rs
- source/scripts/rust/basic/source/basic.rs
- source/tests/metacall_rust_test/source/metacall_rust_test.cpp
Enable rust loader to receive and return String.
> Add string support for rust loader.

- source/loaders/rs_loader/rust/compiler/src/wrapper/array.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/map.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/mod.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/number.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/string.rs
- source/scripts/rust/basic/source/basic.rs
- source/tests/metacall_rust_test/source/metacall_rust_test.cpp
> Enable Rust loader to return Array and Map.

- source/loaders/rs_loader/rust/compiler/src/wrapper/class.rs
- source/ports/node_port/index.js
- source/ports/node_port/test/index.js
- source/ports/py_port/metacall/api.py
- source/ports/py_port/test/test_simple.py
Signed-off-by: Tricster <mediosrity@gmail.com>
Add rust tests for node port and python port.
> Add rust tests for ports.

- .github/workflows/ci.yml
This PR recreates the release CI using GitHub Actions instead of previously used Travis CI and/or GitLab CI.
- No repository variables need to set. The release token is made available directly by GitHub to the workflow.
- Publishing to NPM and Bintray is not yet achieved within this workflow, but may be a part of a later update.
- The Docker and Docker Compose versions aren't fixed; The provided latest versions are used, but that should be alright because the `docker-compose[.*].yml` files already have fixed versioning within them, ensuring no compatibility issues.
- The workflow works in two stages:
- **Build**: This comprises pulling the images, building the image(s) that haven't already been built, and packing the release binaries.
- **Release**: This comprises releasing the built …
> Created the release workflow

- .github/workflows/test.yml
This PR creates a CI workflow to run tests on incoming PRs.
~Fixes #~
Related: #285
> Created Test CI Workflow

- source/loaders/rb_loader/CMakeLists.txt
- source/ports/rb_port/CMakeLists.txt
Add `-fdecspecl` in `CMakeLists.txt` of ruby port.
> Brew ruby for macOS Monterey CI/CD fix

- source/extensions/plugin_extension/source/plugin_extension.cpp
fix depth in directory iterator
> fix depth in directory iterator

- source/cli/metacallcli/CMakeLists.txt
> Remove MACOSX_BUNDLE from source/cli/metacallcli/CMakeLists.txt

- source/loaders/rs_loader/rust/compiler/src/api/function.rs
- source/loaders/rs_loader/rust/compiler/src/lib.rs
- source/loaders/rs_loader/rust/compiler/src/registrator.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/class.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/mod.rs
- source/loaders/rs_loader/rust/src/lib.rs
- source/loaders/rs_loader/rust/src/lifecycle/clear.rs
- source/loaders/rs_loader/rust/src/lifecycle/destroy.rs
- source/loaders/rs_loader/rust/src/lifecycle/discover.rs
- source/loaders/rs_loader/rust/src/lifecycle/execution_path.rs
- source/loaders/rs_loader/rust/src/lifecycle/initialize.rs
- source/loaders/rs_loader/rust/src/lifecycle/load_from_file.rs
- source/loaders/rs_loader/rust/src/lifecycle/load_from_memory.rs
- source/loaders/rs_loader/rust/src/lifecycle/load_from_package.rs
- source/loaders/rs_loader/rust/src/lifecycle/loader.rs
- source/loaders/rs_loader/rust/src/lifecycle/mod.rs
- source/scripts/rust/basic/source/basic.rs
Signed-off-by: Tricster <mediosrity@gmail.com>
> Improve error handling in rs_loader.

- source/cli/plugins/cli_core_plugin/source/cli_core_plugin.cpp
add argument number and type checks in cli-core-plugin
> add argument number and type checks in cli-core-plugin`

- tools/metacall-build.ps1
- tools/metacall-environment.ps1
This PR makes some necessary updates to the Windows CI as guided by Vicente.
CC: @viferga 
> Windows CI Updates

- tools/metacall-environment.ps1
Resolves #348.
CC: @viferga 
Signed-off-by: Param Siddharth <contact@paramsid.com>
> Force deletion to prevent warning/error message

- githooks/pre-commit-clang-format
Added v15 in pre-commit-clang-format
Fixes #(370)
> Updated pre-commit-clang-format

- source/ports/go_port/source/go_port.go
- Refactor and remove useless code.
- Add more type conversions
New feature (non-breaking change which adds functionality)
> ports/go: refactor and add type conversions

- source/ports/go_port/source/go_port.go
- source/ports/go_port/source/go_port_test.go
Support map conversion in go port.
> ports/go: support map type

- .github/workflows/macos-test.yml
- tools/metacall-configure.sh
- tools/metacall-environment.sh
Build Metacall with Ruby support for MacOS and avoid passing Cmake options in CI file
> Build with Ruby and Pass cmake options using env file macOS

- .github/workflows/windows-test.yml
- source/loaders/ts_loader/bootstrap/lib/bootstrap.ts
- tools/metacall-environment.ps1
Typescript CI is passing at 100%.
Fixed the bugs for undefined `register_cb` and `jsx failing` because on un-normalized path comparison
> Typescript windows CI tests

- .github/workflows/macos-test.yml
- tools/metacall-environment.sh
Build Metacall with Web assembly support for MacOS
> Enable Wasm support in macOS 

- .github/workflows/macos-test.yml
- tools/metacall-environment.sh
Build Metacall with NodeJS support for MacOS
Please refer to this [issue](https://github.com/metacall/core/issues/401#issuecomment-1575629562) to see failed tests
> Use Pre-built Node for macOS

- .github/workflows/macos-test.yml
- tools/metacall-environment.sh
Build Metacall with COBOL support for MacOS
> Build MetaCall with Cobol Support for macOS

- .github/workflows/macos-test.yml
- tools/metacall-environment.sh
> Enable GO ports in macOS CI

- .github/CONTRIBUTING.md
Edit on MetaCall documentation to help newbies start contributing faster.
Fixes #387
> Update on CONTRIBUTING.md

- source/plugins/sandbox_plugin/source/sandbox_plugin.cpp
- source/tests/metacall_sandbox_plugin_test/CMakeLists.txt
- source/tests/metacall_sandbox_plugin_test/source/metacall_sandbox_plugin_test.cpp
I have implemented the int sandbox_{category}(void *ctx, bool allow) functions and wrote a test for each one for the following categories of system calls:
IO - Sockets - IPC - Process - Filesystems - Time - Memory - Signals
Feature #465 
> Sandbox Plugin Implementation and Testing

- source/ports/rs_port/src/types/metacall_future.rs
It's some improvements for `MetacallFuture` docs and clarify how to pass data to the `resolver` and `reject`
Closes #523
> docs(rs-port): improve `MetacallFuture` docs and clarify some points
