- source/ports/py_port/package/helper.py
- source/ports/py_port/package/setup.py
These helpers make installation, update and uninstall of MetaCall (CLI, runtime-libs), easy.
this isn't necessarily just for the python package. you can slightly change it to be used globally as a way of managing this project.
the content of /usr/local/lib (`LIB_CONTENT`) is hardcoded for now.
this could improve by storing the filenames in a text file while unpacking ([package data](https://docs.python.org/3/distutils/setupscript.html#installing-package-data)) 
OR, simply move the content inside a directory. so that it can be safely removed (you can still load them with `ldconfig -n -v /usr/local/lib/metacall`)
you can try it out with `pip install -e .`
also replace `docs` with the manual installation guide
here is the output of each command:
**metacall-install**
```
Searching for files …
```
> Add install, update, uninstall helpers.

- source/ports/node_port/package/index.js
I forgot to call the node addon in the JS wrapper file, the wrapper is in charge of checks... before passing it to the c++ realm
> made sure i called the addon in the js wrapper

- .gitignore
- cmake/FindNodeJS.cmake
Node was previously building to /usr/local even though I had specified a prefix with CMAKE_INSTALL_PREFIX. This change forwards the install prefix to node's build script
I also added `.DS_Store` to the gitignore because those files just show up on macOS all the time
> Forward CMAKE_INSTALL_PREFIX to node's "make install"

- cmake/FindNodeJS.cmake
> Fix misspelling (pyhton -> python) in cmake/FindNodeJS.cmake

- source/loaders/ts_loader/bootstrap/lib/bootstrap.ts
I was able to load the `tsconfig.json` file from the root of the project directory. ~~One issue that I came across was that if the `tsconfig.json` file has comments in it, it doesn't work.~~
Edit: works for all types of JSON
This works:
```
{
"compilerOptions": {
"target": "es5",
"module": "commonjs",
"strict": true,
"esModuleInterop": true,
"skipLibCheck": true,
"forceConsistentCasingInFileNames": true,
"outDir": "dist",
"sourceMap": true
}
}
```
This doesn't:
```
{
"compilerOptions": {
"target": "es5", /* comment */
"module": "commonjs",
"strict": true,
"esModuleInterop": true,
"skipLibCheck": true,
"forceConsistentCasingInFileNames": true,
"outDir": "dist",
"sourceMap": true
}
}
```
> feat: load tsconfig from the root of the project

- docs/README.md
This PR fixes a few grammatical errors in the README, along with some erroneous links (e.g. the "Embedding Ruby" example linking to the "Embedding Python" repo).
> Fix links and grammar in docs

- cmake/FindNodeJS.cmake
NodeJS 15.x.x requires icu4c version 67.xx or greater
> Fix icu4c version for NodeJS 15.x.x

- githooks/pre-commit-clang-format
If a path for `clang-format-11` is not found, the hook should instead look for a path for `clang-format` instead. This fails due to the test checking whether the `CLANG_FORMAT` variable is unset, rather than just empty. This PR fixes that.
> Fix clang-format fallback check in pre-commit hook

- source/loaders/mock_loader/include/mock_loader/mock_loader_function_interface.h
The declaration of pointers to struct followed the following format in the loader module.
```c
typedef struct loader_impl_function_type
{
loader_impl_function_create create;
loader_impl_function_interface interface;
loader_impl_function_destroy destroy;
} * loader_impl_function;
```
This was different in mock loader so, changed it to make it uniform everywhere :)
> format fixed for loader_impl_mock_function declaration

- docs/README.md
> updated type system on readme

- source/cli/metacallcli/source/application.cpp
The `load` command in the CLI didn't prompt the user if:
- No loader tag was provided
- An invalid loader tag was provided
This change handles both the cases and raises an invalid usage error in these cases.
Also, the help message have been improved to prompt the user to use the `help` command to see correct usage, or list of available commands.
> Check for valid loader tag in load command

- source/loaders/node_loader/source/node_loader_port.cpp
- source/ports/node_port/index.js
- source/ports/node_port/test/index.js
This PR adds support for local scopes to the Node port through the functions `metacall_load_from_file_export` and  `metacall_load_from_memory_export` which return a handle for accessing the scope, rather than exposing the loaded functions to global scope. It also changes the behaviour of `require` such that it also no longer exports to global scope.
Note that this change breaks some of the test suite for the Node port. Failing tests have been changed accordingly where possible, but the `callback (py)` test has been commented out, as it is broken due to the update. It can be fixed by adding support for classes in the NodeJS loader.
The changes have only been tested on NodeJS 15.x and should probably be tested on NodeJS 10.x before merging.
> Add support for local scopes to Node port

- source/cli/metacallcli/source/application.cpp
The `call` command in the CLI would just print `(null)` if the passed function had not been loaded.
This change validates if the function entered has been loaded, and if not, it prints out an error message and stops the command.
> [CLI] Validate function in call command

- source/loaders/llvm_loader/CMakeLists.txt
- source/loaders/llvm_loader/source/llvm_loader_impl.cpp
Changed required llvm version in llvm_loader from 11.0.1 to 11.0.0
> changed required llvm version in llvm_loader

- source/loaders/java_loader/bootstrap/lib/bootstrap.java
- source/loaders/java_loader/source/java_loader_impl.cpp
- Execution path bootstrap changed to  use a java set to store path and iterate over it to find and load compiled class.
- Bootstrap load_from_file now returns a handle object to metacall which is stored in loader_impl_java_handle_type struct.
> Java loader execution path

- .github/PULL_REQUEST_TEMPLATE.md
- source/loader/source/loader_impl.c
- source/loaders/CMakeLists.txt
- tools/metacall-configure.sh
- tools/metacall-environment.sh
- tools/metacall-runtime.sh
Instead of implementing the path splitting in each loader, the execution_path function will be called every time a new path has to be appended.
TODO: Test it on Windows?? Although it should work as it is right now.
> Add multiple path support for loaders on impl_execution_path

- source/loaders/wasm_loader/source/wasm_loader_impl.c
- source/tests/wasm_loader_test/source/wasm_loader_test.cpp
This PR adds support for multiple return values to the Wasm loader. If a function has more than one return value, calling the function from Metacall will now return an array containing the values instead.
> Wasm loader: Add support for multiple return values

- cmake/FindWasmtime.cmake
- source/loaders/wasm_loader/source/wasm_loader_impl.c
- source/tests/wasm_loader_test/source/wasm_loader_test.cpp
This PR adds support for the Wasm text format in addition to the binary format.
> Add support for Wasm text format

- source/loaders/wasm_loader/source/wasm_loader_impl.c
- source/scripts/wasm/tests/source/exports1.wat
- source/scripts/wasm/tests/source/exports2.wat
- source/scripts/wasm/tests/source/imports.wat
- source/tests/wasm_loader_test/source/wasm_loader_test.cpp
This PR adds support for imports to the Wasm loader using a linker that looks in previously loaded handles for matching exports.
Note that the `LinkingModules` test takes a while to run under Memcheck, so the timeout of 60 seconds may be reached on slower PCs.
> Add support for imports to Wasm loader

- source/loader/source/loader_impl.c
- source/loaders/py_loader/source/py_loader_port.c
- source/ports/py_port/metacall/api.py
- source/scripts/python/wasm_test/source/wasm_test.py
This PR adds support for loading from a package to the Python port using the `import` keyword by checking the file extension.
> Add loading from package to Python port

- source/loaders/wasm_loader/CMakeLists.txt
- source/loaders/wasm_loader/include/wasm_loader/wasm_loader_function.h
- source/loaders/wasm_loader/include/wasm_loader/wasm_loader_handle.h
- source/loaders/wasm_loader/include/wasm_loader/wasm_loader_impl.h
- source/loaders/wasm_loader/source/wasm_loader_function.c
- source/loaders/wasm_loader/source/wasm_loader_handle.c
- source/loaders/wasm_loader/source/wasm_loader_impl.c
Refactor the Wasm loader by splitting it into different files, making private functions static and improving function naming.
> Refactor Wasm loader

- source/dynlink/CMakeLists.txt
- source/dynlink/include/dynlink/dynlink_impl.h
- source/dynlink/source/dynlink_impl.c
- source/dynlink/source/dynlink_impl_unix.c
- source/dynlink/source/dynlink_impl_win32.c
fixes the linux implementation of `dynlink_impl_interface_lib_path_unix` function to pass tests consistently in windows and linux.
> fix unix function to strip lib name

- .github/workflows/test-build-docker-image.yml
This Will Fix the CI/CD Pipeline for the docker images push w/ new pushes to the dockerhub of [`metacall/core`](https://hub.docker.com/r/metacall/core)
Before Merging this PR we will need to add these two Env Vars. in GitHub Secrets of this repo.
```
DOCKER_HUB_USERNAME
```
```
DOCKER_HUB_ACCESS_TOKEN
```
which we can create from here: https://docs.docker.com/docker-hub/access-tokens/
> ci: docker image sync push to dockerhub

- source/cli/metacallcli/source/application.cpp
- source/loaders/rs_loader/rust/api/src/lib.rs
- source/loaders/rs_loader/rust/compiler/src/file.rs
- source/loaders/rs_loader/rust/compiler/src/registrator.rs
- source/loaders/rs_loader/rust/src/lifecycle/clear.rs
- source/loaders/rs_loader/rust/src/lifecycle/discover.rs
Add Rust loader function interface for calling functions.
> add rs loader function interface

- source/loaders/node_loader/CMakeLists.txt
Node v16 uses some API that was added in C++14. Setting the C++ standard to 17 fixes the build errors.
Although, this may affect builds of older node versions that may have been supported before.
Fixes #264
> Set C++ standard to 17 for node loader

- source/loaders/rs_loader/rust/compiler/src/ast.rs
- source/loaders/rs_loader/rust/compiler/src/lib.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/mod.rs
- source/scripts/rust/basic/source/basic.rs
When parsing HIR, the function signatures of `impl` blocks are missing. 
So we parse AST now.
> Parse Rust AST instead of HIR.

- tools/metacall-runtime.sh
This PR fixes incorrect function names for installing java and wasm runtime dependencies.
> fix incorrect function names

- source/CMakeLists.txt
- source/extensions/CMakeLists.txt
- source/extensions/load_extensions/CMakeLists.txt
- source/extensions/load_extensions/include/load_extensions/load_extensions.h
- source/extensions/load_extensions/source/load_extensions.cpp
add extension for loading metacall*.json
> add extension for loading metacall*.json

- source/loaders/rb_loader/CMakeLists.txt
Due to an LLVM bug in AppleClang a flag has to be passed to the compiler in order to fix Ruby building, for reference see : https://github.com/nginx/unit/issues/653#issuecomment-1063524279
- [] I have tested the tests implicated (if any) by my own code and they pass (`make test` or `ctest -VV -R <test-name>`).
@giarve could you please merge this PR, it was tested and worked under KVM-OSX and worked as a fix.
> CMake add compilation flag for Ruby support in Homebrew OSX fix

- source/loaders/ext_loader/source/ext_loader_impl.cpp
- source/tests/metacall_ext_test/source/metacall_ext_test.cpp
fix segfault in metacall-ext-test
> fix segfault in metacall-ext-test

- source/extensions/plugin_extension/source/plugin_extension.cpp
- source/loader/include/loader/loader.h
- source/loader/include/loader/loader_impl.h
- source/loader/source/loader.c
- source/loader/source/loader_impl.c
- source/metacall/include/metacall/metacall.h
- source/metacall/source/metacall.c
metacall-plugin-local-test working properly
> metacall-plugin-local-test working properly

- source/loaders/rs_loader/rust/compiler/src/api/class.rs
- source/loaders/rs_loader/rust/compiler/src/api/function.rs
- source/loaders/rs_loader/rust/compiler/src/api/mod.rs
- source/loaders/rs_loader/rust/compiler/src/api/object.rs
- source/loaders/rs_loader/rust/compiler/src/file.rs
- source/loaders/rs_loader/rust/compiler/src/memory.rs
- source/loaders/rs_loader/rust/compiler/src/package.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/class.rs
- source/loaders/rs_loader/rust/src/lifecycle/clear.rs
- source/loaders/rs_loader/rust/src/lifecycle/destroy.rs
- source/loaders/rs_loader/rust/src/lifecycle/initialize.rs
- source/loaders/rs_loader/rust/src/lifecycle/loader.rs
- source/scripts/rust/basic/source/basic.rs
- source/tests/metacall_rust_load_from_package_test/source/metacall_rust_load_from_package_test.cpp
- source/tests/metacall_rust_test/source/metacall_rust_test.cpp
- source/tests/sanitizer/lsan.supp
Signed-off-by: Tricster <mediosrity@gmail.com>
Fix rs_loader leaks by delaying the destruction of loaded libraries.
Fixes #301 
> Fix rs_loader leaks.

- .github/workflows/test.yml
- source/plugins/backtrace_plugin/source/backtrace_plugin.cpp
- tools/metacall-runtime.sh
Added a Clear Error message when backtrace_plugin load fails
Other Minor fixes
* Replaced `echo "configure cobol"` with `echo "configure backtrace"` [here](https://github.com/metacall/core/blob/develop/tools/metacall-runtime.sh#L242)
* Added backtrace_plugin to test.yml
> Clear Error message when backtrace_plugin load fails

- CMakeLists.txt
Fixes issue with RPATH for MacOS metacall native binary
> Solve RPATH bug for relocatable metacall in MacOS

- source/loaders/node_loader/bootstrap/CMakeLists.txt
- source/loaders/node_loader/bootstrap/lib/bootstrap.js
- source/loaders/node_loader/bootstrap/lib/package-lock.json
- source/loaders/node_loader/bootstrap/lib/package.json
feat: change js parser from cherow to espree
> feat: change js parser from cherow to espree

- source/cli/metacallcli/source/application.cpp
- source/loaders/c_loader/source/c_loader_impl.cpp
Add metacall include path so including metacall/metacall.h `#include <metacall/metacall.h>` works.
Add metacall library path so libtcc can find libmetacall.so.
> Add metacall include path and metacall library path in c loader

- source/ports/py_port/metacall/module_win32.py
When `metacall main.py` used to be run, errors used to get caused as `ctypes` in `module_win32.py` used to try to load a dll which didnt exist, and used to crash immediately without trying all the alternatives. 
Added the check now
> [FIX] Running python on metacall windows works now

- source/loaders/rs_loader/rust/compiler/src/lib.rs
- source/loaders/rs_loader/rust/compiler/src/memory.rs
- source/loaders/rs_loader/rust/compiler/src/wrapper/mod.rs
- source/tests/sanitizer/tsan.supp
Signed-off-by: Tricster <mediosrity@gmail.com>
Move build artifacts of every loaded package into a unique folder to avoid collision when running in parallel.
> [Rust]: Move build artifacts into unique folder.

- tools/metacall-build.ps1
This PR makes sure the step fails even if any of build, test, or install fail in the final build step for Windows.
CC: @viferga 
> Made workflow step fail if any step fails

- source/tests/metacall_python_builtins_test/source/metacall_python_builtins_test.cpp
metacall-python-builtins-test failing in some versions of python because the `ast` module lacks a main function
> remove test failing in different python versions

- .github/workflows/macos-test.yaml
- cmake/CompileOptions.cmake
- tools/metacall-environment-macos.sh
According to this [PR](https://github.com/metacall/core/pull/248) the only thing that was not completed is the macOS pipeline, so I created the pipeline for it.
It is just running tests, for now, it does not support any language yet.
The ci for macOS is falling at three test cases which are:
-  15- detour-test
-  4 - log-custom-test (Subprocess aborted)
-  35 - metacall-dynlink-path-test
you can view full logs from [here ](https://github.com/ahmedihabb2/core/actions/runs/4129078853/jobs/7134289663)
> Add macos pipeline and scripts

- .github/workflows/macos-test.yml
- tools/metacall-environment-macos.sh
Build Metacall with Python support for MacOS 
The following tests FAILED:
4 - log-custom-test (SEGFAULT)
33 - metacall-dynlink-path-test (Failed)
34 - metacall-library-path-without-env-vars-test (Failed)
you can view full logs from [here](https://github.com/ahmedihabb2/core/actions/runs/4276457026/jobs/7444558733)
> feat: Build with Python support for MacOS

- tools/metacall-environment.ps1
Simply passes NPM_EXECUTABLE as an parameter to cmake for the tests failing in TS Bootstrap, etc
> add npm exec path to cmake vars

- .github/workflows/macos-test.yml
- tools/metacall-environment-macos.sh
Build Metacall with Java support for MacOS 
The following tests FAILED:
4 - log-custom-test (SEGFAULT)
53 - metacall-dynlink-path-test (Failed)
54 - metacall-library-path-without-env-vars-test (Failed)
you can view full logs from [here](https://github.com/ahmedihabb2/core/actions/runs/4527734836/jobs/7973861776)
> feat: Build with Java support for MacOS

- source/ports/go_port/source/go_port.go
- source/ports/go_port/source/go_port_test.go
- Small refactorings.
- Remove useless buffer of all channels. (consumer always faster than producer)
> ports/go: add more type conversions and tests

- source/ports/go_port/source/go_port.go
- source/ports/go_port/source/go_port_test.go
Support buffer type for go port.
> ports/go: support buffer type

- source/ports/rs_port/Cargo.toml
- source/ports/rs_port/src/macros.rs
- source/ports/rs_port/src/parsers.rs
- source/ports/rs_port/src/types/metacall_class.rs
- source/ports/rs_port/src/types/metacall_exception.rs
- source/ports/rs_port/src/types/metacall_function.rs
- source/ports/rs_port/src/types/metacall_future.rs
- source/ports/rs_port/src/types/metacall_null.rs
- source/ports/rs_port/src/types/metacall_object.rs
- source/ports/rs_port/src/types/metacall_pointer.rs
- source/ports/rs_port/src/types/metacall_value.rs
- source/ports/rs_port/tests/loaders_test.rs
- source/ports/rs_port/tests/metacall_test.rs
> Improve rs_port stage 5

- docs/README.md
Grammatical issues pertaining to the 'a/an' indefinite articles are fixed. Some of the text has been rephrased for better readability. 
As this is a minor update to the documentation only, a corresponding issue is not created.
> docs: fixed 'a/an' issues and rephrased some of the text

- README.md
- docs/README.md
This PR aims to fix a few typos, and grammatical errors in:
- README.md in the root directory.
- README.md for `docs` dir.
> nit: Fix typos & grammatical errors

- .github/workflows/benchmark.yml
Now benchmark CI pushes the results to another repo to keep track of benchmark history and to keep the main repo clean
- [Download the previous benchmark results](https://github.com/metacall/core/blob/1aeaede8ad542bac27ebd934bbc0220fc1c9c813/.github/workflows/benchmark.yml#L69C1-L76C1) removed as we do not need cache anymore as we compare with previous results from the other repo
- [Output directory changed](https://github.com/metacall/core/blob/1aeaede8ad542bac27ebd934bbc0220fc1c9c813/.github/workflows/benchmark.yml#L92C13-L92C60) as when it was /bench/matrix.os, the benchmark action will search for previous results in /bench directory, although we store them directly on the repo using matrix.os in order to access them using metacall.github.io/benchmarks/ubuntu-latest not …
> Update Benchmark CI to use another repo

- cmake/FindNodeJS.cmake
- source/cli/plugins/CMakeLists.txt
- source/loaders/node_loader/source/node_loader_impl.cpp
- source/loaders/node_loader/source/node_loader_port.cpp
- source/loaders/ts_loader/source/ts_loader_impl.cpp
- source/tests/CMakeLists.txt
- source/tests/metacall_node_multithread_deadlock_test/CMakeLists.txt
- source/tests/metacall_node_multithread_deadlock_test/source/main.cpp
- source/tests/metacall_node_multithread_deadlock_test/source/metacall_node_multithread_deadlock_test.cpp
> First PoC for solving threading issues in node loader.

- source/ports/rs_port/src/loaders.rs
- source/ports/rs_port/tests/inlines_test.rs
- source/ports/rs_port/tests/loaders_test.rs
> fix: incorrectly calculating the size of script that is loaded from memory

- .github/workflows/linux-test.yml
- .github/workflows/macos-test.yml
- .github/workflows/windows-test.yml
In this I have added the repository dispatch so that it will trigger the linux-dist repo, only if it passes all the linux tests mentioned.
Fixes #505 Connect Core CI with Distributable's Repo
- [ X I have tested my code with `OPTION_BUILD_ADDRESS_SANITIZER` or `./docker-compose.sh test-address-sanitizer &> output` and `OPTION_TEST_MEMORYCHECK`.
- [ X I have tested my code with `OPTION_BUILD_THREAD_SANITIZER` or `./docker-compose.sh test-thread-sanitizer &> output`.
> Linux CI Repository Dispatch Test added

- .github/workflows/release.yml
**PR Description**:
This PR updates the release workflow to use the latest versions of key GitHub Actions and tools, ensuring enhanced stability and compatibility. 
Changes:
- Updated `upload-artifact` action to version `v4`.
- Updated `download-artifact` action to the latest version `4.1.8`.
- Upgraded GHR (GitHub Release) tool to the latest version for improved release management.
@viferga
> Update Release Workflow and Upload/Download Artifact Actions to Latest Versions

- source/ports/node_port/index.js
The modern API for node port has the following design for most of the languages:
```js
require('metacall')
const { sum } = require('./sum.py')
const const result = sum(1, 2)
console.log(result) // 3
```
However, not for C loader.
It used to result in the following error:
```
Exception in node_loader_trampoline_load_from_file while loading: [ 'main.js' ] /home/adarsh/gsoc/metacall-tut/bun-ffi/sum.c:1
double sum(double a, double b)
^^^
SyntaxError: Unexpected identifier
at internalCompileFunction (node:internal/vm:73:18)
at wrapSafe (node:internal/modules/cjs/loader:1274:20)
at Module._compile (node:internal/modules/cjs/loader:1320:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
at Module.load (node:internal/modules/cjs/loader:1197:32)
at Module._load …
```
> feat: Add C loader support for node_port

- source/ports/rs_port/src/cast.rs
- source/ports/rs_port/src/lib.rs
- source/ports/rs_port/src/types/metacall_exception.rs
- source/ports/rs_port/src/types/metacall_value.rs
- source/ports/rs_port/tests/metacall_test.rs
…types
Implement metacall_box for passing function arguments with different types
- [x- I have commented my code, particularly in hard-to-understand areas.
> Implement metacall_box for passing function arguments with different types

- .github/workflows/release-rust.yml
- source/ports/rs_port/build.rs
> fix and refactor: rust port not finding metacall shared libraries and config files 

- source/ports/rs_port/README.md
> edit rs port readme and providing relatable links

- source/environment/include/environment/environment_variable_path.h
- source/environment/source/environment_variable_path.c
- source/portability/include/portability/portability_path.h
- source/portability/source/portability_path.c
- source/tests/portability_path_test/source/portability_path_test.cpp
- Get rid of some buffer overruns
- make more functions return more sensible things on NULL arguments
- properly DOCUMENT each function
- Add const type qualifiers where applicable
- Replace some string functions and loops with memcpy
This fixed some broken tests when I cloned with a "." in my parent path (like /github.com/metacall/core/...)
> Reimplement and bugfix some path functions
